### ISSUE TITLE
Add a license to specify licensing terms

### ISSUE THREAD

**Issue by vmallet** [pd95/SwiftUI-Continuity-Camera#1]
This is a great simple example of how to integrate Continuity Camera into a SwftUI app. It would be great if you could explicitly specify the licensing terms of the code in case you are open to having other people reuse this work. 

Without a license the default licensing applies which is pretty restrictive:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

(from: [Licensing A Repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository))

Maybe an MIT license?

Thank you for the example!

**Comment by pd95** [comment]
Thank you for the interest in this project.

I've added a MIT license as suggested, to allow reuse of any part. (Anyway, it isn't rocket science what I did 😉)
